
name: GithubActions-Flask-ver.2
env:
    PACKAGE_NAME: "Flask-WEB-server"
    PACKAGE_VERSION: "${{ github.sha }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print NAME + VER
        run:
          echo "PackNAME:${{ env.PACKAGE_NAME }}" &&
          echo "Github package version:${{ env.PACKAGE_VERSION }}"
          
      - name: Check software versions
        run:
          python3 -V &&
          aws --version &&
          pip -V
          
      - name: Install Flask
        run: 
          pip install Flask &&
          flask --version
          
      - name: Clone repo to the container (OS)
        uses: actions/checkout@v1
        
      - name: Current location
        run: 
           pwd &&
           ls -lah
        
      - name: Run Flask-WEB-server
        run:
          python3 application.py 2>&1 &
          
      - name: Check accessibility
        run:
         netstat -tunlp |grep 5000 &&
         curl http://127.0.0.1:5000/main
